### PR TITLE
Add entry point

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
Whoops. Seems the entry point was only added after 0.3. Waiting for 0.4 release then :)

**Comment by jasmainak** [comment]
@hoechenberger I don't know what you're exactly doing but I trust that it will be good once the CIs are good :-)

**Comment by hoechenberger** [comment]
@jasmainak Adding support for the "entry points" that will create a command-line interface, see https://github.com/mne-tools/mne-bids/blob/4234280958775c445861d2c93b2b41d5c040391a/setup.py#L58-L60 :)

**Comment by jasmainak** [comment]
yep that's the only thing in the diff I understood in this PR :)

**Comment by sappelhoff** [comment]
maybe something to look into after 0.4 is released :-)

**Comment by hoechenberger** [comment]
Right, will look into this tomorrow, thanks @sappelhoff

**Comment by hoechenberger** [comment]
Oh wait, 0.4 hasn't been released yet :D

**Comment by sappelhoff** [comment]
> Oh wait, 0.4 hasn't been released yet :D

I am on it :D

**Comment by hoechenberger** [comment]
Closing in favor of #3

**Pull request closed without merging**
